included:
    - Sources
    - Package.swift

excluded:
    - .build
    - Submodules

opt_in_rules:
    - array_init
    - attributes
    - closure_end_indentation
    - closure_spacing
    - empty_count
    - explicit_init
    - extension_access_modifier
    - fatal_error_message
    - first_where
    - let_var_whitespace
    - literal_expression_end_indentation
    - nimble_operator
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call

disabled_rules:
    - attributes
    - multiple_closures_with_trailing_closure
    - trailing_comma
    - vertical_parameter_alignment_on_call
    - void_return

custom_rules:
    disable_print:
        name: "print usage"
        regex: "((\\bprint)|(Swift\\.print))\\s*\\("
        message: "User app.logger or request.logger instead of print"
        severity: warning

# Default Rule Configuration
type_name:
    min_length: 2

identifier_name:
    min_length: 2
    allowed_symbols: "_"
    excluded:
        - x
        - f
        - i

file_length:
    warning: 500
    error: 1000

function_body_length: 50

line_length: 200

cyclomatic_complexity:
    ignores_case_statements: true

large_tuple:
    warning: 6
    error: 10

nesting:
    type_level:
        warning: 2
    function_level:
        warning: 10